ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_otp VARCHAR(6);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_otp_expires_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS inactivity_alerted_at TIMESTAMP;
