mindmap
  root((com.towin))
    account/
      AccountController.java
      AccountService.java
    admin/
      dto/
        AdminConnectionResponse.java
        AdminMessageResponse.java
        AdminNeedResponse.java
        AdminReportResponse.java
        AdminReviewResponse.java
        AdminUserResponse.java
        AdminVerificationResponse.java
      AdminController.java
      AdminService.java
    assistant/
      controller/
        AssistantController.java
      dto/
        ChatMessage.java
        ChatRequest.java
        ChatResponse.java
      service/
        AssistantService.java
        GroqClient.java
    auth/
      controller/
        AuthController.java
        OAuthController.java
      dto/
        AuthResponse.java
        ChangePasswordRequest.java
        ForgotPasswordRequest.java
        GuestLoginRequest.java
        LoginRequest.java
        OAuthCompleteRequest.java
        OAuthExchangeRequest.java
        OAuthExchangeResponse.java
        PhoneVerifyRequest.java
        RegisterRequest.java
        ResetPasswordRequest.java
        VerifyEmailRequest.java
        VerifyIdResponse.java
      oauth/
        CookieUtils.java
        HttpCookieOAuth2AuthorizationRequestRepository.java
        OAuth2FailureHandler.java
        OAuth2SuccessHandler.java
        OneTimeCodeStore.java
      security/
        IpRateLimiter.java
        JwtUtil.java
        LoginRateLimiter.java
        OtpRateLimiter.java
        PasswordPolicy.java
      service/
        AuthService.java
        OAuthService.java
    common/
      config/
        KafkaConfig.java
        OpenApiConfig.java
        RedisConfig.java
        S3Config.java
        SchedulingConfig.java
        WebSocketConfig.java
        WebSocketSecurityConfig.java
      converter/
        TrustLevelConverter.java
      dto/
        ErrorResponse.java
      entity/
        PendingRegistration.java
        User.java
      enums/
        ApplicationStatus.java
        BackgroundCheckStatus.java
        ConnectionStatus.java
        ConnectionType.java
        Gender.java
        LookingForType.java
        MessageType.java
        NeedCategory.java
        NeedSchedule.java
        NeedStatus.java
        NeedUrgency.java
        TrustLevel.java
        UserRole.java
        VerificationStatus.java
      exception/
        GlobalExceptionHandler.java
        RateLimitException.java
      messaging/
        ConnectionEvent.java
        ConnectionEventConsumer.java
        ConnectionEventProducer.java
      repository/
        PendingRegistrationRepository.java
        UserRepository.java
      security/
        JwtAuthFilter.java
        SecurityConfig.java
      seed/
        AdminSeeder.java
        DemoActivityInterceptor.java
        DemoDataSeeder.java
        DemoResetCoordinator.java
        DemoWebConfig.java
      service/
        EmailService.java
        PostHogService.java
        S3Service.java
        TrustScoreService.java
    connection/
      controller/
        ConnectionController.java
      dto/
        ConnectionRequest.java
        ConnectionResponse.java
        RespondToConnectionRequest.java
      entity/
        Connection.java
      repository/
        ConnectionRepository.java
      service/
        ConnectionService.java
    discovery/
      controller/
        DiscoveryController.java
      dto/
        DiscoveredUserResponse.java
        DiscoveryFilter.java
      service/
        DiscoveryService.java
    emergency/
      controller/
        EmergencyController.java
      dto/
        EmergencyContactRequest.java
        EmergencyContactResponse.java
      entity/
        EmergencyContact.java
      repository/
        EmergencyContactRepository.java
      service/
        EmergencyContactService.java
        InactivityCheckService.java
        SosService.java
    feedback/
      controller/
        FeedbackController.java
      dto/
        FeedbackRequest.java
        FeedbackResponse.java
      entity/
        Feedback.java
      repository/
        FeedbackRepository.java
      service/
        FeedbackService.java
    geocoding/
      dto/
        GeoResult.java
      GeocodingController.java
      GeocodingService.java
    messaging/
      controller/
        MessageController.java
      dto/
        MessageRequest.java
        MessageResponse.java
      entity/
        Message.java
      repository/
        MessageRepository.java
      service/
        MessageService.java
    need/
      controller/
        NeedController.java
      dto/
        ApplicantDto.java
        ApplyRequest.java
        NeedRequest.java
        NeedResponse.java
      entity/
        Need.java
        NeedApplication.java
      repository/
        NeedApplicationRepository.java
        NeedRepository.java
      service/
        NeedService.java
    profile/
      controller/
        ProfileController.java
      dto/
        ElderProfileRequest.java
        HelperProfileRequest.java
        PhoneUpdateRequest.java
        ProfileResponse.java
      entity/
        ElderProfile.java
        HelperProfile.java
      repository/
        ElderProfileRepository.java
        HelperProfileRepository.java
      service/
        ProfileService.java
    report/
      controller/
        ReportController.java
      dto/
        ReportRequest.java
      entity/
        Report.java
      repository/
        ReportRepository.java
      service/
        ReportService.java
    review/
      controller/
        ReviewController.java
      dto/
        ReviewRequest.java
        ReviewResponse.java
      entity/
        Review.java
      repository/
        ReviewRepository.java
      service/
        ReviewService.java
    streak/
      controller/
        StreakController.java
      dto/
        StreakResponse.java
      entity/
        UserStreak.java
      repository/
        UserStreakRepository.java
      service/
        StreakService.java
    trust/
      controller/
        TrustController.java
      dto/
        TrustActionRequest.java
        TrustScoreBreakdownResponse.java
        TrustStatusResponse.java
      entity/
        TrustProgressionLog.java
      repository/
        TrustProgressionLogRepository.java
      service/
        TrustService.java
    ToWinApplication.java
